Repository AstarNetwork/astar-docs, pull requests merged in 2023-04, with the labels that each got.

#324 Release notes github template
  .github/release.yml
Labels: enhancement

#329 Update interact_with_xc20.md
  docs/build/builder-guides/leverage_parachains/interact_with_xc20.md
Labels: enhancement

#327 Enforcing labels for PRs
  .github/workflows/enforce-labels.yml
Labels: ci

#321 Extensive explanation of Wasm contracts transaction fees
  docs/build/wasm/ask_contracts.md
  docs/build/wasm/basic-contract.md
  docs/build/wasm/community.md
  docs/build/wasm/contract_environment/_category_.json
  docs/build/wasm/dsls.md
  docs/build/wasm/from-zero-to-ink-hero/_category_.json
  docs/build/wasm/ink-dev.md
  docs/build/wasm/interact/_category_.json
  docs/build/wasm/nodes-clients.md
  docs/build/wasm/psps.md
  docs/build/wasm/smart-contract-wasm.md
  docs/build/wasm/swanky-suite/_category_.json
  docs/build/wasm/tooling/_category_.json
  docs/build/wasm/transaction-fees.md
Labels: documentation
