Repository AstarNetwork/astar-docs, pull requests merged in 2023-12, with the labels that each got.

#539 Add tutorial to bridge SBY token with LayerZero
  docs/build/zkEVM/integrations/bridges-relays/AstarEVM-zkEVM.md
  docs/build/zkEVM/integrations/bridges-relays/astar-bridge.md
Labels: documentation

#540 feat: add wasm states for AU manual transfer
  docs/build/astar-beta-labs/account-unification/index.md
Labels: documentation

#541 Update/Add The Graph node and subgraphs walkthrough
  docs/build/integrations/_category_.json
  docs/build/integrations/indexers/thegraph.md
  docs/build/zkEVM/integrations/indexers/img/thegraph10-subgraph.png
  docs/build/zkEVM/integrations/indexers/img/thegraph11-initializesubgraph.png
  docs/build/zkEVM/integrations/indexers/img/thegraph12-installgraphcli.png
  docs/build/zkEVM/integrations/indexers/img/thegraph13-yarngraphcli.png
  docs/build/zkEVM/integrations/indexers/img/thegraph2-connectwallet.png
  docs/build/zkEVM/integrations/indexers/img/thegraph3-connectwallet2.png
  docs/build/zkEVM/integrations/indexers/img/thegraph4-createfirstSubgraph.png
  docs/build/zkEVM/integrations/indexers/img/thegraph5-createfirstAPI.png
  docs/build/zkEVM/integrations/indexers/img/thegraph6-createAPIkey.png
  docs/build/zkEVM/integrations/indexers/img/thegraph7-freequeries.png
  docs/build/zkEVM/integrations/indexers/img/thegraph8-subgraphstudio.png
  docs/build/zkEVM/integrations/indexers/img/thegraph9-createsubgraph.png
  docs/build/zkEVM/integrations/indexers/index.md
  docs/build/zkEVM/integrations/indexers/thegraph.md
Labels: documentation

#543 Update README.md - Remove version so it's relevant w/o changes
  README.md
Labels: bug

#545 Update Astar Docs with references to Astar Network Audit Reports repository
  docs/build/astar-beta-labs/account-unification/index.md
  docs/getting-started.md
Labels: enhancement

#544 polish the graph technical docs
  docs/build/integrations/indexers/thegraph.md
  docs/build/zkEVM/integrations/indexers/thegraph.md
Labels: documentation

#547 update node sections
  docs/build/nodes/full-node.md
  docs/build/nodes/index.md
  docs/build/nodes/node-commands.md
  docs/build/zkEVM/zk-node/index.md
Labels: documentation

#548 update build landing page with new features
  docs/build/index.md
Labels: documentation

#549 updated hybrid Inflation model on Astar
  docs/learn/tokenomics2/Inflation.md
  docs/learn/tokenomics2/index.md
Labels: documentation

#552 add SubWallet section into docs/use/mange-wallets/wallet-providers
  docs/use/manage-wallets/wallet-providers/subwallet.md
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-1.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-10.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-11.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-12.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-13.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-14.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-15.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-16.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-17.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-18.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-19.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-2.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-20.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-21.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-22.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-23.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-24.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-25.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-26.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-27.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-28.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-29.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-3.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-30.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-31.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-32.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-33.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-34.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-35.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-36.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-4.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-5.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-6.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-7.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-8.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-9 copy.png
  static/docs/use/manage-wallets/wallet-providers/img/subwallet/subwallet-9.png
Labels: documentation

#554 dApp Staking v3
  docs/learn/dapp-staking.md
  docs/learn/index.md
Labels: documentation

#553 Tokenomics 2.0 docs
  docs/learn/index.md
  docs/learn/tokenomics2/Inflation.md
  docs/learn/tokenomics2/index.md
  docs/learn/tokenomics2/legacy_inflation.md
Labels: documentation
