Repository AstarNetwork/astar-docs, pull requests merged in 2023-11, with the labels that each got.

#499 Add ZK RPC node setup
  docs/build/nodes/evm-tracing-node.md
  docs/build/zkEVM/zk-node/setup-rpc-node.md
Labels: documentation

#493 Shiden transaction fee update
  docs/learn/tokenomics2/img/Astar-Block-Consumption.jpeg
  docs/learn/tokenomics2/tokenomics2-network-fees.md
Labels: documentation

#500 Adds Dwellir zkEVM endpoint
  docs/build/zkEVM/quickstart.md
Labels: documentation

#502 update-ledger-native
  docs/build/integrations/wallets/ledger/ledger-native.md
Labels: documentation

#503 Update docs-integration-request.md
  docs-integration-request.md
Labels: documentation

#505 MetaMask Astar Wallet Snap
  docs/use/manage-wallets/wallet-providers/img/01.png
  docs/use/manage-wallets/wallet-providers/img/02.png
  docs/use/manage-wallets/wallet-providers/img/03.png
  docs/use/manage-wallets/wallet-providers/img/04.png
  docs/use/manage-wallets/wallet-providers/img/05.png
  docs/use/manage-wallets/wallet-providers/img/06.png
  docs/use/manage-wallets/wallet-providers/img/07.png
  docs/use/manage-wallets/wallet-providers/img/08.png
  docs/use/manage-wallets/wallet-providers/img/09.png
  docs/use/manage-wallets/wallet-providers/img/10.png
  docs/use/manage-wallets/wallet-providers/img/11.png
  docs/use/manage-wallets/wallet-providers/img/12.png
  docs/use/manage-wallets/wallet-providers/img/13.png
  docs/use/manage-wallets/wallet-providers/img/14.png
  docs/use/manage-wallets/wallet-providers/img/15.png
  docs/use/manage-wallets/wallet-providers/img/18.png
  docs/use/manage-wallets/wallet-providers/img/19.png
  docs/use/manage-wallets/wallet-providers/img/20.png
  docs/use/manage-wallets/wallet-providers/metamask-astar-snap.md
Labels: documentation

#507 Fix/typo binaries
  docs/build/nodes/archive-node/binary.md
  docs/build/nodes/archive-node/docker.md
  docs/build/nodes/collator/secure_setup_guide/building_node.md
  docs/build/nodes/collator/spinup_collator.md
  docs/build/nodes/evm-tracing-node.md
  docs/build/nodes/node-commands.md
  docs/build/nodes/rpi-cheat-sheet.md
Labels: documentation

#504 Adds Particle Network tutorial in "wallets" section
  docs/build/integrations/wallets/particle-network.md
Labels: documentation

#506 Adds ChainIDE for Astar
  docs/build/EVM/chainide-for-astar-evm/_category_.json
  docs/build/EVM/chainide-for-astar-evm/index.md
  docs/build/EVM/chainide-for-astar-evm/setup.md
  docs/build/EVM/chainide-for-astar-evm/use.md
  docs/build/wasm/chainide-for-astar-wasm/_category_.json
  docs/build/wasm/chainide-for-astar-wasm/index.md
  docs/build/wasm/chainide-for-astar-wasm/setup.md
  docs/build/wasm/chainide-for-astar-wasm/use.md
Labels: documentation

#510 Gelato Web3 Functions Docs
  docs/build/zkEVM/integrations/automation-off-chain/_category_.json
  docs/build/zkEVM/integrations/automation-off-chain/img/functions.png
  docs/build/zkEVM/integrations/automation-off-chain/img/hardhat-init.png
  docs/build/zkEVM/integrations/automation-off-chain/img/triggers.png
  docs/build/zkEVM/integrations/automation-off-chain/img/w3f.png
  docs/build/zkEVM/integrations/automation-off-chain/index.md
  docs/build/zkEVM/integrations/automation-off-chain/w3f.md
Labels: documentation

#509 Update figure function
  src/components/figure.tsx
Labels: documentation

#511 feat: upgrade to docusaurus v3, mdx fixes and gas station
  docs/build/Introduction/node_interact.md
  docs/build/builder-guides/integration_toolings/using-sidecar.md
  docs/build/environment/chopsticks.md
  docs/build/environment/gas-station.md
  docs/build/environment/local-network.md
  docs/build/integrations/account-abstraction/banana/index.md
  docs/build/integrations/api/gas_api.md
  docs/build/integrations/bridges/cbridge.md
  docs/build/integrations/indexers/bluez.md
  docs/build/integrations/indexers/subscan.md
  docs/build/integrations/indexers/thegraph.md
  docs/build/integrations/node-providers/blast.md
  docs/build/integrations/node-providers/pinknode.md
  docs/build/integrations/wallets/subwallet.md
  docs/build/nodes/archive-node/binary.md
  docs/build/nodes/archive-node/docker.md
  docs/build/nodes/archive-node/nginx.md
  docs/build/nodes/collator/secure_setup_guide/building_node.md
  docs/build/nodes/evm-tracing-node.md
  docs/build/nodes/rpi-cheat-sheet.md
  docs/build/nodes/snapshots.md
  docs/build/wasm/from-zero-to-ink-hero/dex/Pair/storage.md
  docs/build/wasm/swanky-suite/node.md
  docs/build/zkEVM/fee.md
  docs/build/zkEVM/integrations/account-abstraction/relayers/gelato-relay.md
  docs/build/zkEVM/integrations/account-abstraction/safe--aa/index.md
  docs/build/zkEVM/zk-node/setup-local-node.md
  docs/build/zkEVM/zk-node/setup-rpc-node.md
  docs/learn/interoperability/xcm/building-with-xcm/xc-remote-transact.md
  docs/learn/interoperability/xcm/integration/asset-registration.md
  docs/learn/interoperability/xcm/integration/hrmp.md
  docs/tutorials/from-zero-to-ink-hero/dex/Pair/storage.md
  docs/use/manage-assets/dex.md
  docs/use/manage-assets/manage-xc20-with-metamask.md
  docs/use/manage-wallets/create-multisig.md
  docs/use/manage-wallets/create-wallet.md
  docs/use/manage-wallets/wallet-providers/metamask-astar-snap.md
  docusaurus.config.js
  i18n/ja/docusaurus-plugin-content-docs/current/user-guides/create-multisig.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-guides/create-wallet.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-guides/dex.md
  package.json
  tsconfig.json
  yarn.lock
Labels: documentation, enhancement, dependencies

#512 create-promotion
  docs/build/dapp-staking/for-devs/create-promotion.md
  docs/build/dapp-staking/for-devs/img/promotion-card.png
Labels: enhancement

#513 Update Biconomy examples
  docs/build/integrations/account-abstraction/biconomy/biconomy-sdk.md
Labels: documentation

#514 minor updates to create-promotion
  docs/build/dapp-staking/for-devs/create-promotion.md
Labels: documentation

#516 Fix/broken-links.md
  docs/build/nodes/archive-node/index.md
  docs/learn/networks.md
  docs/learn/polkadot_relay.md
Labels: documentation

#525 add-promotion-card-requirement
  docs/build/dapp-staking/for-devs/create-promotion.md
Labels: documentation

#526 Updates ChainIDE for Astar
  docs/build/EVM/chainide-for-astar-evm/img/chainIDE0.png
  docs/build/EVM/chainide-for-astar-evm/use.md
  docs/build/wasm/chainide-for-astar-wasm/img/chainIDE56.png
  docs/build/wasm/chainide-for-astar-wasm/use.md
Labels: documentation

#527 remove backticks from mdx-code-block formatted code
  docs/build/EVM/index.md
  docs/build/EVM/infra/index.md
  docs/build/EVM/interact/index.md
  docs/build/astar-beta-labs/index.md
  docs/build/builder-guides/index.md
  docs/build/dapp-staking/for-devs/index.md
  docs/build/dapp-staking/for-stakers/index.md
  docs/build/dapp-staking/index.md
  docs/build/environment/index.md
  docs/build/index.md
  docs/build/integrations/account-abstraction/index.md
  docs/build/integrations/index.md
  docs/build/integrations/indexers/index.md
  docs/build/integrations/node-providers/index.md
  docs/build/integrations/wallets/index.md
  docs/build/nodes/collator/secure_setup_guide/index.md
  docs/build/nodes/index.md
  docs/build/wasm/contract_environment/index.md
  docs/build/wasm/from-zero-to-ink-hero/index.md
  docs/build/wasm/index.md
  docs/build/wasm/interact/index.md
  docs/build/wasm/tooling/index.md
  docs/build/zkEVM/index.md
  docs/build/zkEVM/integrations/account-abstraction/index.md
  docs/build/zkEVM/integrations/account-abstraction/relayers/index.md
  docs/build/zkEVM/integrations/account-abstraction/web3auth/index.md
  docs/build/zkEVM/integrations/automation-off-chain/index.md
  docs/build/zkEVM/integrations/index.md
  docs/build/zkEVM/integrations/oracles/index.md
  docs/build/zkEVM/smart-contracts/index.md
  docs/build/zkEVM/zk-node/index.md
  docs/learn/interoperability/xcm/building-with-xcm/index.md
  docs/learn/interoperability/xcm/index.md
  docs/learn/interoperability/xcm/using-xcm/index.md
  docs/learn/tokenomics2/index.md
  docs/tutorials/from-zero-to-ink-hero/index.md
  docs/tutorials/index.md
  docs/use/index.md
  docs/use/manage-wallets/wallet-providers/index.md
  i18n/ja/docusaurus-plugin-content-docs/current/dapp-staking/for-devs/index.md
  i18n/ja/docusaurus-plugin-content-docs/current/dapp-staking/for-stakers/index.md
  i18n/ja/docusaurus-plugin-content-docs/current/dapp-staking/index.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-guides/index.md
Labels: documentation

#522 Enable Japanese translation
  docusaurus.config.js
  i18n/ja/code.json
  i18n/ja/docusaurus-plugin-content-docs/current.json
  i18n/ja/docusaurus-plugin-content-docs/current/learn/zkEVM/faq.md
  i18n/ja/docusaurus-plugin-content-docs/current/learn/zkEVM/img/astar-zkevm-value.png
  i18n/ja/docusaurus-plugin-content-docs/current/learn/zkEVM/index.md
  i18n/ja/docusaurus-theme-classic/footer.json
  i18n/ja/docusaurus-theme-classic/navbar.json
Labels: enhancement, translation

#523 update asset-list
  docs/learn/interoperability/asset-list.md
  docs/learn/interoperability/xcm/asset-list.md
Labels: documentation

#529 update ledger tutorials
  docs/build/integrations/wallets/ledger/ledger-evm.md
  docs/build/integrations/wallets/ledger/ledger-native.md
Labels: documentation

#524 Add sentio2zk evm
  docs/build/zkEVM/integrations/indexers/img/sentio1.png
  docs/build/zkEVM/integrations/indexers/img/sentio10.png
  docs/build/zkEVM/integrations/indexers/img/sentio11.png
  docs/build/zkEVM/integrations/indexers/img/sentio12.png
  docs/build/zkEVM/integrations/indexers/img/sentio13.png
  docs/build/zkEVM/integrations/indexers/img/sentio14.png
  docs/build/zkEVM/integrations/indexers/img/sentio15.png
  docs/build/zkEVM/integrations/indexers/img/sentio16.png
  docs/build/zkEVM/integrations/indexers/img/sentio17.png
  docs/build/zkEVM/integrations/indexers/img/sentio18.png
  docs/build/zkEVM/integrations/indexers/img/sentio19.png
  docs/build/zkEVM/integrations/indexers/img/sentio2.png
  docs/build/zkEVM/integrations/indexers/img/sentio20.png
  docs/build/zkEVM/integrations/indexers/img/sentio21.png
  docs/build/zkEVM/integrations/indexers/img/sentio22.png
  docs/build/zkEVM/integrations/indexers/img/sentio23.png
  docs/build/zkEVM/integrations/indexers/img/sentio3.png
  docs/build/zkEVM/integrations/indexers/img/sentio4.png
  docs/build/zkEVM/integrations/indexers/img/sentio5.png
  docs/build/zkEVM/integrations/indexers/img/sentio55.png
  docs/build/zkEVM/integrations/indexers/img/sentio6.png
  docs/build/zkEVM/integrations/indexers/img/sentio7.png
  docs/build/zkEVM/integrations/indexers/img/sentio8.png
  docs/build/zkEVM/integrations/indexers/img/sentio9.png
  docs/build/zkEVM/integrations/indexers/sentio-debugger.md
  docs/build/zkEVM/smart-contracts/img/end-product-nft-code.png
  docs/build/zkEVM/smart-contracts/img/flatten-code-remix.png
  docs/build/zkEVM/smart-contracts/img/hardhat-init.png
  docs/build/zkEVM/smart-contracts/img/input-object.png
  docs/build/zkEVM/smart-contracts/img/json.png
  docs/build/zkEVM/smart-contracts/img/proj-created-outcome.png
  docs/build/zkEVM/smart-contracts/using-hardhat.md
  docs/build/zkEVM/smart-contracts/verify-smart-contract.md
  docs/build/zkEVM/smart-contracts/write-smart-contract.md
Labels: documentation

#531 Fix Raspberry cheatsheet
  docs/build/nodes/rpi-cheat-sheet.md
Labels: documentation

#532 Add ZKEVM_NET Param
  docs/build/zkEVM/zk-node/setup-rpc-node.md
Labels: documentation

#533 Small Particle Network tutorial edits
  docs/build/zkEVM/integrations/account-abstraction/particle-network.md
Labels: documentation

#534 Update asset-list.md
  docs/learn/interoperability/xcm/asset-list.md
Labels: documentation

#537 Finished translating getting started section
  i18n/ja/docusaurus-plugin-content-docs/current/getting-started.md
Labels: documentation
