Repository AstarNetwork/astar-docs, pull requests merged in 2023-05, with the labels that each got.

#331 revise and rename 'the problems Astar solves' to 'What is Astar network'
  docs/about/astar.md
  docs/build/index.md
Labels: documentation

#333 Monthly release
  .github/workflows/monthly-release.yml
Labels: ci

#335 release fix
  .github/workflows/monthly-release.yml
Labels: ci

#336 Add images to wanchain bridge page
  docs/integrations/bridges/img/wanchain1.png
  docs/integrations/bridges/img/wanchain2.png
  docs/integrations/bridges/img/wanchain3.png
  docs/integrations/bridges/img/wanchain4.png
  docs/integrations/bridges/img/wanchain5.png
  docs/integrations/bridges/wanchain.md
Labels: enhancement

#338 Broken links check
  .github/workflows/broken-links.yml
  .lycheeignore
Labels: ci

#339 Assets import to metamask update.
  docs/xcm/using-xcm/img/7.png
  docs/xcm/using-xcm/img/8.png
  docs/xcm/using-xcm/manage-xc20-with-metamask.md
Labels: documentation

#344 add ledger native staking tutorial
  docs/integrations/wallets/ledger/img/native/ledger1.png
  docs/integrations/wallets/ledger/img/native/ledger2.png
  docs/integrations/wallets/ledger/img/native/ledger3.png
  docs/integrations/wallets/ledger/img/native/ledger4.png
  docs/integrations/wallets/ledger/img/native/ledger5.png
  docs/integrations/wallets/ledger/img/native/ledger6.png
  docs/integrations/wallets/ledger/img/native/ledger7.png
  docs/integrations/wallets/ledger/ledger-native.md
Labels: documentation

#349 Update of SubQuery Indexing
  docs/integrations/indexers/img/4.png
  docs/integrations/indexers/subquery.md
Labels: documentation

#343 Update ledger-evm.md
  docs/integrations/wallets/ledger/ledger-evm.md
Labels: documentation

#348 feat: added Astar-AI
  docusaurus.config.js
  package.json
  static/astarAi.js
  yarn.lock
Labels: enhancement

#356 Fix node docker base path
  docs/nodes/archive-node/docker.md
  docs/nodes/node-commands.md
Labels: documentation

#355 improve phrasing for developers
  docs/build/index.md
Labels: documentation

#354 Missing sudo command to change authority
  docs/nodes/collator/secure_setup_guide/building_node.md
Labels: documentation

#353 Update asset-list.md
  docs/xcm/asset-list.md
Labels: documentation

#346 docs: pallet-proxy introduction
  docs/user-guides/img/33.png
  docs/user-guides/img/34.png
  docs/user-guides/img/35.png
  docs/user-guides/img/36.png
  docs/user-guides/img/37.png
  docs/user-guides/img/38.png
  docs/user-guides/pallet-proxy.md
Labels: documentation

#357 Update asset-list.md
  docs/xcm/asset-list.md
Labels: documentation

#358 add toggle explanation
  docs/integrations/wallets/ledger/img/native/ledger8.png
  docs/integrations/wallets/ledger/ledger-native.md
Labels: enhancement

#351 Tutorial for ink! cross contract call and e2e test
  docs/build/wasm/from-zero-to-ink-hero/dex/_category_.json
  docs/build/wasm/from-zero-to-ink-hero/manic-minter/_category_.json
  docs/build/wasm/from-zero-to-ink-hero/manic-minter/manic-contract.md
  docs/build/wasm/from-zero-to-ink-hero/manic-minter/manic-e2e.md
  docs/build/wasm/from-zero-to-ink-hero/manic-minter/manic-minter.md
  docs/build/wasm/from-zero-to-ink-hero/manic-minter/manic-setup.md
Labels: documentation

#337 Chopsticks & E2E Tests
  docs/build/environment/chopsticks.md
Labels: documentation
