Repository AstarNetwork/astar-docs, pull requests merged in 2023-10, with the labels that each got.

#450 add Greg's web2-web3 migration overview
  docs/build/builder-guides/leverage_parachains/mint-nfts-crust.md
  docs/tutorials/index.md
  docs/tutorials/migrating-from-web2-web3/_category_.json
  docs/tutorials/migrating-from-web2-web3/img/Web2-Web3-Migration.png
  docs/tutorials/migrating-from-web2-web3/img/figure1.png
  docs/tutorials/migrating-from-web2-web3/index.md
  docs/tutorials/migrating-from-web2-web3/web2-web3-overview.md
Labels: documentation

#453 Megan misc fixes
  docs/build/EVM/index.md
  docs/build/EVM/infra/img-verification-cookbook/img
  docs/build/EVM/infra/img/Untitled.png
  docs/build/EVM/infra/img/Untitled1.png
  docs/build/EVM/infra/img/Untitled2.png
  docs/build/EVM/infra/img/Untitled3.png
  docs/build/EVM/infra/img/Untitled4.png
  docs/build/EVM/infra/img/Untitled5.png
  docs/build/EVM/infra/img/Untitled6.png
  docs/build/EVM/infra/img/Untitled7.png
  docs/build/EVM/infra/img/Untitled8.png
  docs/build/EVM/infra/img/flatten.jpg
  docs/build/EVM/infra/verify_smart_contract.md
  docs/build/Introduction/index.md
  docs/build/builder-guides/astar_features/use_remix.md
  docs/build/builder-guides/hacking/general.md
  docs/build/builder-guides/hacking/hack_evm.md
  docs/build/builder-guides/hacking/hack_wasm.md
  docs/build/builder-guides/hacking/index.md
  docs/build/builder-guides/index.md
  docs/build/builder-guides/integration_toolings/use-python.md
  docs/build/environment/faucet.md
  docs/build/environment/index.md
  docs/build/img/build.png
  docs/build/img/builderguides.png
  docs/build/img/environment.png
  docs/build/img/evm.png
  docs/build/img/gradient1.jpg
  docs/build/img/gradient2.jpg
  docs/build/img/gradient3.jpg
  docs/build/img/gradient4.jpg
  docs/build/img/gradient5.jpg
  docs/build/img/gradient6.jpg
  docs/build/img/gradient7.jpg
  docs/build/img/gradient8.jpg
  docs/build/img/gradient9.jpg
  docs/build/img/introduction.png
  docs/build/img/wasm.png
  docs/build/index.md
  docs/build/wasm/community.md
  docs/build/wasm/index.md
  docs/getting-started.md
  static/docs/build/img/build.png
  static/docs/build/img/builderguides.png
  static/docs/build/img/environment.png
  static/docs/build/img/evm.png
  static/docs/build/img/gradient1.jpg
  static/docs/build/img/gradient2.jpg
  static/docs/build/img/gradient3.jpg
  static/docs/build/img/gradient4.jpg
  static/docs/build/img/gradient5.jpg
  static/docs/build/img/gradient6.jpg
  static/docs/build/img/gradient7.jpg
  static/docs/build/img/gradient8.jpg
  static/docs/build/img/gradient9.jpg
  static/docs/build/img/introduction.png
  static/docs/build/img/wasm.png
Labels: documentation

#452 Add USDC to asset-list.md
  docs/learn/interoperability/xcm/asset-list.md
Labels: documentation

#451 add Sentio Debugger page
  docs/build/integrations/indexers/img/sentio1.png
  docs/build/integrations/indexers/img/sentio10.png
  docs/build/integrations/indexers/img/sentio11.png
  docs/build/integrations/indexers/img/sentio12.png
  docs/build/integrations/indexers/img/sentio13.png
  docs/build/integrations/indexers/img/sentio14.png
  docs/build/integrations/indexers/img/sentio15.png
  docs/build/integrations/indexers/img/sentio16.png
  docs/build/integrations/indexers/img/sentio17.png
  docs/build/integrations/indexers/img/sentio18.png
  docs/build/integrations/indexers/img/sentio19.png
  docs/build/integrations/indexers/img/sentio2.png
  docs/build/integrations/indexers/img/sentio20.png
  docs/build/integrations/indexers/img/sentio21.png
  docs/build/integrations/indexers/img/sentio22.png
  docs/build/integrations/indexers/img/sentio23.png
  docs/build/integrations/indexers/img/sentio3.png
  docs/build/integrations/indexers/img/sentio4.png
  docs/build/integrations/indexers/img/sentio5.png
  docs/build/integrations/indexers/img/sentio55.png
  docs/build/integrations/indexers/img/sentio6.png
  docs/build/integrations/indexers/img/sentio7.png
  docs/build/integrations/indexers/img/sentio8.png
  docs/build/integrations/indexers/img/sentio9.png
  docs/build/integrations/indexers/sentio.md
Labels: documentation

#449 XCM Precomplies - doc update
  docs/build/EVM/precompiles/xcm.md
Labels: documentation

#454 update docs integration request doc
  docs-integration-request.md
  docs/getting-started.md
  infrastructure_pull_request_template.md
Labels: documentation

#456 Create Enkrypt Wallet
  docs/use/manage-wallets/wallet-providers/_category_.json
  docs/use/manage-wallets/wallet-providers/enkrypt-wallet.md
  docs/use/manage-wallets/wallet-providers/index.md
Labels: documentation

#457 update docs integration request
  docs-integration-request.md
Labels: documentation

#458 Update XCM/xtoken precompiles
  docs/build/EVM/precompiles/index.md
  docs/build/EVM/precompiles/xcm.md
  docs/build/EVM/precompiles/xcm/_category.json
  docs/build/EVM/precompiles/xcm/native-transfer.md
  docs/build/EVM/precompiles/xcm/transfer-asssets.md
  docs/build/EVM/precompiles/xcm/withdraw-assets.md
  docs/build/EVM/precompiles/xcm/xcm.md
Labels: documentation

#461 feat: add AU technical docs
  docs/build/astar-beta-labs/account-unification/_category_.json
  docs/build/astar-beta-labs/account-unification/img/lookup.png
  docs/build/astar-beta-labs/account-unification/img/with.png
  docs/build/astar-beta-labs/account-unification/img/without.png
  docs/build/astar-beta-labs/account-unification/index.md
Labels: documentation

#462 remove placeholder for account unification docs
  docs/build/astar-beta-labs/account-abstraction/_category_.json
  docs/build/astar-beta-labs/account-abstraction/index.md
Labels: documentation

#463 add AU user-guide
  docs/build/astar-beta-labs/account-unification/img/guide01.png
  docs/build/astar-beta-labs/account-unification/img/guide02.png
  docs/build/astar-beta-labs/account-unification/img/guide03.png
  docs/build/astar-beta-labs/account-unification/img/guide04.png
  docs/build/astar-beta-labs/account-unification/img/guide05.png
  docs/build/astar-beta-labs/account-unification/img/guide06.png
  docs/build/astar-beta-labs/account-unification/users_guide.md
Labels: documentation

#465 update docs-integration-request.md
  docs-integration-request.md
Labels: documentation

#459 Archive Batch Precompile
  docs/build/EVM/precompiles/.batch.md
  docs/build/EVM/precompiles/index.md
Labels: documentation

#467 fix replit codeblock syntax
  docs/build/environment/light-client.md
Labels: documentation

#466 Update astar-tokens.md - fix broken table
  docs/learn/astar-tokens.md
Labels: bug

#470 Small fixes
  docs/build/zkEVM/bridge-to-zkevm.md
  docs/build/zkEVM/faq/zkevm-eth-faq.md
  docs/build/zkEVM/img/metamask-sepolia-select.png
  docs/build/zkEVM/quickstart.md
  docs/build/zkEVM/smart-contracts/using-hardhat.md
  docs/build/zkEVM/smart-contracts/verify-smart-contract.md
  docs/build/zkEVM/zkevm-faucet.md
Labels: documentation

#471 Update native XCM tx with v3 example
  docs/learn/interoperability/xcm/building-with-xcm/img/2.png
  docs/learn/interoperability/xcm/building-with-xcm/native-transactions.md
Labels: documentation

#472 Remove note about not using weights v2
  docs/build/wasm/transaction-fees.md
Labels: bug

#468 Feat/transaction fee alignment
  docs/learn/tokenomics2/_category_.json
  docs/learn/tokenomics2/img/Astar-Block-Consumption.jpeg
  docs/learn/tokenomics2/index.md
  docs/learn/tokenomics2/tokenomics2-network-fees.md
Labels: documentation

#474 add Startale RPC; minor updates
  docs-integration-request.md
  docs/build/environment/endpoints.md
  docs/build/environment/ink_environment.md
  docs/build/zkEVM/integrations/node-providers/startale-labs.md
  docs/learn/img/inflation_1.png
  docs/learn/img/tokenomics_1.png
  docs/learn/tokenomics.md
Labels: documentation

#475 zkEVM updates
  docs/build/EVM/developer-tooling/img/thirdweb-explore.png
  docs/build/EVM/developer-tooling/thirdweb.md
  docs/build/index.md
  docs/build/integrations/index.md
  docs/build/integrations/oracles/acurast.md
  docs/build/zkEVM/integrations/bridges-relays/astar-bridge.md
  docs/build/zkEVM/integrations/indexers/index.md
  docs/build/zkEVM/integrations/indexers/subquery.md
  docs/getting-started.md
  docs/use/evm-guides/_category_.json
  docusaurus.config.js
  src/components/HomepageFeatures/index.tsx
Labels: documentation

#476 fix: zkevm gas fee calculation
  docs/build/zkEVM/fee.md
Labels: documentation

#481 fix dependabot CI
  .github/workflows/firebase-hosting-pull-request.yml
Labels: ci

#477 Create pyth.md
  docs/build/zkEVM/integrations/oracles/pyth.md
Labels: documentation

#478 feat(): adds acurast as zkevm oracle
  docs/integrations/oracles/acurast.md
Labels: documentation

#483 move Acurast & fix broken URL
  docs/build/integrations/oracles/acurast.md
  docs/build/zkEVM/integrations/oracles/acurast.md
Labels: documentation

#485 Update quickstart.md
  docs/build/zkEVM/quickstart.md
Labels: documentation

#486 chore(): correct content for acurast evm/wasm & zkEVM
  docs/build/integrations/oracles/acurast.md
  docs/build/zkEVM/integrations/oracles/acurast.md
Labels: documentation

#487 add Web3Auth and Astar Safe
  docs/build/integrations/wallets/astar-safe.md
  docs/build/integrations/wallets/img/networks.png
  docs/build/zkEVM/integrations/account-abstraction/index.md
  docs/build/zkEVM/integrations/account-abstraction/web3auth/_category_.json
  docs/build/zkEVM/integrations/account-abstraction/web3auth/index.md
  docs/build/zkEVM/integrations/account-abstraction/web3auth/web3auth-zkatana.md
  docs/build/zkEVM/integrations/wallets/astar-safe.md
Labels: documentation

#488 Gelato relay
  docs-integration-request.md
  docs/build/zkEVM/integrations/account-abstraction/relayers/_category_.json
  docs/build/zkEVM/integrations/account-abstraction/relayers/gelato-relay.md
  docs/build/zkEVM/integrations/account-abstraction/relayers/index.md
Labels: documentation

#464 Lighthouse docs added
  docs/build/EVM/precompiles/xcm/xcm.md
  docs/build/builder-guides/leverage_parachains/lighthouse-encryption.md
  docs/build/builder-guides/leverage_parachains/mint-nfts-crust.md
  docs/build/builder-guides/leverage_parachains/mint-nfts-lighthouse.md
Labels: documentation

#491 Remove gas station chapter2
  docs/build/zkEVM/fee.md
  docs/build/zkEVM/zkevm-gas-station.md
Labels: documentation

#490 Update block explorer and fix RPi doc
  docs/build/nodes/rpi-cheat-sheet.md
  docs/build/zkEVM/integrations/oracles/acurast.md
  docs/build/zkEVM/integrations/oracles/pyth.md
  docs/build/zkEVM/quickstart.md
  docs/build/zkEVM/smart-contracts/using-hardhat.md
  docs/build/zkEVM/smart-contracts/verify-smart-contract.md
Labels: documentation

#492 Updating the Subsquid guide
  docs/build/integrations/indexers/img/subsquidGraphiql.png
  docs/build/integrations/indexers/subsquid.md
  docs/build/zkEVM/integrations/indexers/subsquid.md
Labels: documentation

#494 Add Blockscout doc link, fix Gelato explorer
  docs/build/zkEVM/quickstart.md
  docs/build/zkEVM/smart-contracts/verify-smart-contract.md
Labels: documentation

#498 Feat/gelato aa Adding Safe Account Abstraction SDK
  docs/build/zkEVM/integrations/account-abstraction/index.md
  docs/build/zkEVM/integrations/account-abstraction/relayers/_category_.json
  docs/build/zkEVM/integrations/account-abstraction/safe--aa/_category_.json
  docs/build/zkEVM/integrations/account-abstraction/safe--aa/index.md
Labels: documentation

#497 Update quickstart.md
  docs/build/zkEVM/quickstart.md
Labels: documentation
