Repository AstarNetwork/astar-docs, pull requests merged in 2023-08, with the labels that each got.

#402 update rpi page
  docs/nodes/rpi-cheat-sheet.md
Labels: documentation

#403 Clarify EVM tracing
  docs/build/EVM/evm-debug-api.md
  docs/build/nodes/evm-tracing-node.md
Labels: documentation

#404 Add Subscan to Indexers & GraphQL section
  docs/build/integrations/indexers/covalent.md
  docs/build/integrations/indexers/img/subscan/contract_detail.png
  docs/build/integrations/indexers/img/subscan/contract_verify.png
  docs/build/integrations/indexers/img/subscan/contracts.png
  docs/build/integrations/indexers/img/subscan/failed.png
  docs/build/integrations/indexers/img/subscan/read_call.png
  docs/build/integrations/indexers/img/subscan/transaction_detail.png
  docs/build/integrations/indexers/img/subscan/transactions.png
  docs/build/integrations/indexers/img/subscan/verified_contract.png
  docs/build/integrations/indexers/subscan.md
Labels: documentation

#405 Update xcm-transactions.md
  docs/learn/xcm/using-xcm/xcm-transactions.md
Labels: documentation

#407 Add dependencies label authorized
  .github/workflows/enforce-labels.yml
Labels: ci

#410 Update firebase-hosting-pull-request.yml
  .github/workflows/firebase-hosting-pull-request.yml
Labels: ci

#411 Remove XC20 revert code docs
  docs/build/builder-guides/leverage_parachains/interact_with_xc20.md
  docs/learn/xcm/building-with-xcm/create-xc20-assets.md
Labels: documentation

#412 feat: updated ledger-native guide
  docs/build/integrations/wallets/ledger/ledger-native.md
Labels: documentation

#423 upgrade to docusaurus 2.4.1
  package.json
  yarn.lock
Labels: dependencies

#414 Restore links removed temporarily during docs-revamp merge
  docs/build/EVM/evm-debug-api.md
  docs/build/EVM/precompiles/xc20.md
  docs/build/EVM/precompiles/xcm.md
  docs/build/Introduction/create_account.md
  docs/build/builder-guides/leverage_parachains/interact_with_xc20.md
  docs/build/environment/endpoints.md
  docs/build/environment/zombienet-testing.md
  docs/build/index.md
  docs/build/integrations/indexers/subsquid.md
  docs/build/integrations/indexers/thegraph.md
  docs/build/integrations/node-providers/index.md
  docs/build/integrations/wallets/ledger/ledger-native.md
  docs/build/nodes/archive-node/binary.md
  docs/build/nodes/archive-node/docker.md
  docs/build/nodes/archive-node/index.md
  docs/build/nodes/collator/learn.md
  docs/build/nodes/collator/requirements.md
  docs/build/nodes/collator/secure_setup_guide/building_node.md
  docs/build/nodes/collator/spinup_collator.md
  docs/build/nodes/evm-tracing-node.md
  docs/build/nodes/full-node.md
  docs/build/nodes/node-maintenance.md
  docs/build/wasm/contract_environment/explorers.md
  docs/getting-started.md
  docs/learn/ecosystem/polkadot.md
  docs/learn/xcm/faq.md
  docs/learn/xcm/integration/add-to-portal.md
  docs/use/Manage assets/manage-xc20-with-metamask.md
  docs/use/Manage assets/transfer-tokens.md
  docs/use/Manage assets/xcm-transactions.md
  docs/use/user-guides/create-wallet.md
  docusaurus.config.js
  src/pages/index.tsx
Labels: documentation

#416 Update manual_claim.md
  docs/use/Staking/manual_claim.md
Labels: documentation

#415 add batch precompile docs
  docs/build/EVM/precompiles/batch.md
  docs/build/EVM/precompiles/index.md
Labels: documentation

#417 Update troubleshooting.md
  docs/use/troubleshooting.md
Labels: documentation

#421 Mideg/use links
  docs/use/Manage assets/transfer-tokens.md
  docs/use/Manage wallets/use-proxies.md
  docs/use/Manage wallets/using-a-multisig-account-on-astar-portal.md
Labels: documentation

#425 Add DIA Wasm Oracle to Build section
  docs/build/integrations/oracles/dia-wasm.md
Labels: documentation

#426 Update create_account.md
  docs/build/Introduction/create_account.md
Labels: documentation

#431 unblock pipeline; prep for merge of megan_fixMain
  docs/use/Manage assets/manage-xc20-with-metamask.md
  docs/use/Manage assets/transfer-tokens.md
  docs/use/Manage assets/xcm-transactions.md
  docs/use/Manage wallets/using-a-multisig-account-on-astar-portal.md
Labels: documentation

#436 Update firebase-hosting-pull-request.yml
  .github/workflows/firebase-hosting-pull-request.yml
Labels: ci

#437 Megan misc fixes
  docs/build/integrations/wallets/transak.md
  docs/use/Manage assets/_category_.json
  docs/use/user-guides/_category_.json
  docs/use/user-guides/create-wallet.md
  docs/use/user-guides/index.md
  src/components/HomepageFeatures/index.tsx
Labels: documentation

#440 add main section overviews; subsection index cards
  docs/learn/index.md
  docs/tutorials/index.md
  docs/use/index.md
Labels: documentation
