Repository AstarNetwork/astar-docs, pull requests merged in 2024-01, with the labels that each got.

#561 Update Troubleshooting Page
  docs/use/img/Troubleshooting_dApp_Staking.png
  docs/use/troubleshooting.md
Labels: documentation

#562 Improve voting subperiod
  docs/learn/dapp-staking.md
Labels: documentation

#564 Update dapp-staking.md
  docs/learn/dapp-staking.md
Labels: documentation

#566 Divers ink! doc update and chain extension
  docs/build/wasm/basic-contract.md
  docs/build/wasm/contract_environment/chain-extension/assets-ce.md
  docs/build/wasm/contract_environment/chain-extension/chain_extensions.md
  docs/build/wasm/contract_environment/verification.md
  docs/build/wasm/nodes-clients.md
  docs/build/wasm/transaction-fees.md
Labels: documentation

#559 Update astar-tokens.md
  docs/learn/astar-tokens.md
Labels: documentation

#567 Inflation docs - minor fixes
  docs/learn/tokenomics2/index.md
  docs/learn/tokenomics2/legacy_inflation.md
  docs/learn/tokenomics2/tokenomics2-network-fees.md
Labels: documentation

#569 Follow-up PR Assets Chain Extension
  docs/build/wasm/contract_environment/chain-extension/assets-ce.md
Labels: documentation

#568 Consolidating dApp Staking v3 docs
  docs/build/dapp-staking/index.md
  docs/learn/dapp-staking-v3/_category_.json
  docs/learn/dapp-staking-v3/dapp-staking-faq.md
  docs/learn/dapp-staking-v3/dapp-staking-protocol.md
  docs/learn/dapp-staking-v3/index.md
  docs/learn/index.md
Labels: documentation, dependencies

#571 Update multilocation.md - broken link
  docs/learn/interoperability/xcm/integration/multilocation.md
Labels: bug

#560 Update glossary.md
  docs/learn/glossary.md
Labels: documentation

#572 dApp promotion card page update
  docs/build/dapp-staking/for-devs/create-promotion.md
Labels: documentation

#555 Update subwallet.md
  docs/use/manage-wallets/wallet-providers/subwallet.md
Labels: documentation

#565 Fix docker deployment command
  docs/build/nodes/archive-node/docker.md
Labels: documentation

#575 update asset-list
  docs/learn/interoperability/asset-list.md
  docs/learn/interoperability/xcm/asset-list.md
Labels: documentation

#580 Image update for dApp Staking V3 user guide
  docs/use/dapp-staking/for-stakers/img/13_header.png
  docs/use/dapp-staking/for-stakers/img/8.png
  docs/use/dapp-staking/for-stakers/img/MydApps_Panel_1.png
  docs/use/dapp-staking/for-stakers/img/Networks.png
  docs/use/dapp-staking/for-stakers/img/Projects_page.png
  docs/use/dapp-staking/for-stakers/img/Staking_Page.png
  docs/use/dapp-staking/for-stakers/img/Staking_Page_2.png
  docs/use/dapp-staking/for-stakers/img/Staking_Page_3.png
  docs/use/dapp-staking/for-stakers/img/Staking_Panel_1.png
  docs/use/dapp-staking/for-stakers/img/Unbonding_1.png
  docs/use/dapp-staking/for-stakers/img/Unbonding_2.png
  docs/use/dapp-staking/for-stakers/img/Vote_Page.png
  docs/use/dapp-staking/for-stakers/manage-dApp-Staking.md
  docs/use/dapp-staking/for-stakers/move-staked-tokens.md
  docs/use/dapp-staking/for-stakers/staking.md
  docs/use/dapp-staking/for-stakers/unstaking.md
Labels: documentation

#582 dApp Staking V3 Dev Guide
  docs/use/dapp-staking/dapp-staking-v2/for-devs/_category_.json
  docs/use/dapp-staking/dapp-staking-v2/for-devs/index.md
  docs/use/dapp-staking/dapp-staking-v2/for-devs/register-dapp.md
  docs/use/dapp-staking/dapp-staking-v2/for-devs/requirements.md
  docs/use/dapp-staking/for-devs/create-promotion.md
  docs/use/dapp-staking/for-devs/img/Project.png
  docs/use/dapp-staking/for-devs/img/Promotion_card_1.png
  docs/use/dapp-staking/for-devs/img/Promotion_card_2.png
  docs/use/dapp-staking/for-devs/img/Registration_1.png
  docs/use/dapp-staking/for-devs/img/Registration_2.png
  docs/use/dapp-staking/for-devs/img/Registration_banner.png
  docs/use/dapp-staking/for-devs/img/dApp_owner_page.png
  docs/use/dapp-staking/for-devs/img/dApp_page.png
  docs/use/dapp-staking/for-devs/img/dApp_rewards.png
  docs/use/dapp-staking/for-devs/index.md
  docs/use/dapp-staking/for-devs/manage-dApp-Staking.md
  docs/use/dapp-staking/for-devs/register-dapp.md
  docs/use/dapp-staking/for-devs/requirements.md
  docs/use/dapp-staking/for-stakers/index.md
  docs/use/dapp-staking/for-stakers/manage-dApp-Staking.md
  docs/use/dapp-staking/for-stakers/move-staked-tokens.md
  docs/use/dapp-staking/for-stakers/unstaking.md
  docs/use/dapp-staking/index.md
Labels: documentation

#577 Added chapter for NFT-API on zkAstar
  docs/build/zkEVM/integrations/nft-api/_category_.json
  docs/build/zkEVM/integrations/nft-api/index.md
Labels: documentation

#585 Update images for Dev Guide
  docs/use/dapp-staking/for-devs/create-promotion.md
  docs/use/dapp-staking/for-devs/img/Project.png
  docs/use/dapp-staking/for-devs/img/Promotion_card_3.png
  docs/use/dapp-staking/for-devs/img/Registration_banner.png
  docs/use/dapp-staking/for-devs/img/dApp_owner_page_2.png
  docs/use/dapp-staking/for-devs/img/dApp_page_2.png
  docs/use/dapp-staking/for-devs/img/dApp_rewards.png
  docs/use/dapp-staking/for-devs/manage-dApp-Staking.md
  docs/use/dapp-staking/for-devs/register-dapp.md
Labels: documentation

#589 Update Images
  docs/use/dapp-staking/for-devs/create-promotion.md
  docs/use/dapp-staking/for-devs/img/Promotion_card_2.png
  docs/use/dapp-staking/for-devs/img/Registration_1.png
  docs/use/dapp-staking/for-devs/img/Registration_2.png
  docs/use/dapp-staking/for-devs/img/dApp_owner_page.png
  docs/use/dapp-staking/for-devs/img/dApp_page.png
  docs/use/dapp-staking/for-devs/manage-dApp-Staking.md
  docs/use/dapp-staking/for-devs/register-dapp.md
Labels: documentation

#587 Fix typo in Audit Reports at getting-started page
  docs/getting-started.md
Labels: documentation

#591 Update: openbrush tag correction
  docs/tutorials/from-zero-to-ink-hero/nft/Wizard/wizard.md
Labels: documentation

#578 Rent fee for asset creation
  docs/build/builder-guides/leverage_parachains/interact_with_xc20.md
  docs/learn/interoperability/xcm/building-with-xcm/create-xc20-assets.md
  docs/learn/tokenomics2/tokenomics2-network-fees.md
Labels: documentation

#592 Update unregister docs
  docs/learn/dapp-staking/dapp-staking-protocol.md
Labels: documentation
