Repository AstarNetwork/astar-docs, pull requests merged in 2024-03, with the labels that each got.

#618 Add Astar ZK RPC node page
  docs/build/zkEVM/zk-node/setup-mainnet-rpc-node.md
  docs/build/zkEVM/zk-node/setup-testnet-rpc-node.md
Labels: documentation

#619 Improve DS doc for devs + fix JP doc
  docs/use/dapp-staking/for-devs/img/Polkadotjs_1.png
  docs/use/dapp-staking/for-devs/img/Polkadotjs_2.png
  docs/use/dapp-staking/for-devs/img/Polkadotjs_3.png
  docs/use/dapp-staking/for-devs/img/Polkadotjs_4.png
  docs/use/dapp-staking/for-devs/img/Subwallet_1.webp
  docs/use/dapp-staking/for-devs/img/Subwallet_2.webp
  docs/use/dapp-staking/for-devs/img/Subwallet_3.png
  docs/use/dapp-staking/for-devs/img/Talisman_1.webp
  docs/use/dapp-staking/for-devs/img/Talisman_2.webp
  docs/use/dapp-staking/for-devs/img/Talisman_3.webp
  docs/use/dapp-staking/for-devs/register-dapp.md
  i18n/ja/docusaurus-plugin-content-docs/current/build/zkEVM/zk-node/setup-local-rollup-node.md
  i18n/ja/docusaurus-plugin-content-docs/current/build/zkEVM/zk-node/setup-rpc-node.md
  i18n/ja/docusaurus-plugin-content-docs/current/build/zkEVM/zkevm-faucet.md
  i18n/ja/docusaurus-plugin-content-docs/current/use/_category_.json
  i18n/ja/docusaurus-plugin-content-docs/current/use/dapp-staking/for-stakers/index.md
Labels: documentation, translation

#622 Add quickstart page and update FAQs
  docs/build/zkEVM/faq/zkevm-general-faq.md
  docs/build/zkEVM/faq/zkevm-protocol-faq.md
  docs/learn/zkEVM/quickstart.md
Labels: documentation

#621 Update Rarible links for zk
  docs/build/zkEVM/integrations/nft-api/index.md
Labels: documentation

#626 Update zkEVM RPC info
  docs/build/zkEVM/quickstart.md
  docs/use/dapp-staking/_category_.json
  docs/use/manage-assets/img/XC20_EVM_1.png
  docs/use/manage-assets/img/XC20_EVM_2.png
  docs/use/manage-assets/img/XC20_EVM_3.png
  docs/use/manage-assets/manage-xc20-with-metamask.md
  docs/use/troubleshooting.md
Labels: documentation

#628 Add zkEVM User Guides
  docs/build/zkEVM/quickstart.md
  docs/learn/zkEVM/quickstart.md
  docs/use/dapp-staking/for-devs/register-dapp.md
  docs/use/zkevm-guides/Bridge-Ethereum.md
  docs/use/zkevm-guides/_category_.json
  docs/use/zkevm-guides/img/Bridge_ETH_1.png
  docs/use/zkevm-guides/img/Bridge_ETH_2.png
  docs/use/zkevm-guides/img/Bridge_ETH_3.png
  docs/use/zkevm-guides/img/Bridge_ETH_4.png
  docs/use/zkevm-guides/img/Bridge_ETH_5.png
  docs/use/zkevm-guides/img/Bridge_ETH_6.png
  docs/use/zkevm-guides/img/Bridge_ETH_7.png
  docs/use/zkevm-guides/img/Bridge_ETH_8.png
  docs/use/zkevm-guides/img/Setup_zkevm_1.png
  docs/use/zkevm-guides/index.md
  docs/use/zkevm-guides/set-up-zkevm.md
Labels: documentation

#625 Updated LZ bridge instructions
  docs/build/zkEVM/integrations/bridges-relays/AstarEVM-zkEVM.md
Labels: documentation

#616 Add Astar zkEVM Cannonical Contracts Page
  docs/build/zkEVM/cannonical-zkevm-contracts.md
  docs/build/zkEVM/faq/_category_.json
  docs/build/zkEVM/integrations/_category_.json
Labels: documentation

#629 Update cannonical-zkevm-contracts.md
  docs/build/zkEVM/cannonical-zkevm-contracts.md
Labels: documentation

#632 Add Astar EVM <> Astar zkEVM Bridge User Guide
  docs/use/zkevm-guides/Bridge-Astar-EVM.md
  docs/use/zkevm-guides/Bridge-Ethereum.md
  docs/use/zkevm-guides/img/Stargate_1.png
  docs/use/zkevm-guides/img/Stargate_2.png
Labels: documentation

#631 Adding Crossmint under zkEVM category as NFT
  docs/build/zkEVM/integrations/nft-checkout/_category_.json
  docs/build/zkEVM/integrations/nft-checkout/crossmint.md
  docs/build/zkEVM/integrations/nft-checkout/index.md
Labels: documentation

#634 Adding Crossmint as one of the wallet integrations on zkEVM
  docs/build/zkEVM/integrations/wallets/crossmint.md
Labels: documentation

#637 docs update: adding NFT Collection category under zkEVM integrations
  docs/build/zkEVM/integrations/nft-checkout/_category_.json
  docs/build/zkEVM/integrations/nft-collections/_category_.json
  docs/build/zkEVM/integrations/nft-collections/crossmint.md
  docs/build/zkEVM/integrations/nft-collections/index.md
Labels: documentation

#638 update locale: disable Polish
  docusaurus.config.js
Labels: bug

#639 User Guide: ASTR Liquid Staking zkEVM
  docs/use/zkevm-guides/ASTR-Liquid-Staking.md
  docs/use/zkevm-guides/Bridge-Astar-EVM.md
  docs/use/zkevm-guides/img/Bifrost_1.png
  docs/use/zkevm-guides/img/Bifrost_2.png
  docs/use/zkevm-guides/img/Bifrost_3.png
  docs/use/zkevm-guides/img/Bifrost_4.png
  i18n/ja/docusaurus-plugin-content-docs/current/use/zkevm-guides/Bridge-Astar-EVM.md
Labels: documentation, translation

#641 Update particle-network.md
  docs/build/zkEVM/integrations/account-abstraction/particle-network.md
Labels: documentation

#640 Fixed the font style error.
  i18n/ja/docusaurus-plugin-content-docs/current/use/zkevm-guides/Bridge-Astar-EVM.md
Labels: translation

#633 New Shiden slot calculation formula
  docs/learn/dapp-staking/dapp-staking-protocol.md
Labels: documentation

#642 small change but changed faucet translation
  i18n/ja/docusaurus-plugin-content-docs/current/build/zkEVM/zkevm-faucet.md
Labels: translation

#635 Feat/bridge zk japanese
  docs/use/zkevm-guides/Bridge-Ethereum.md
  i18n/ja/docusaurus-plugin-content-docs/current/use/zkevm-guides/Bridge-Ethereum.md
Labels: documentation, translation

#644 added supra oracle to docs
  docs/build/integrations/oracles/dia-wasm.md
  docs/build/integrations/oracles/dia.md
  docs/build/zkEVM/integrations/oracles/pyth.md
  docs/build/zkEVM/integrations/oracles/supra.md
Labels: documentation

#645 update subsquid, quickstart
  docs/build/integrations/indexers/subsquid.md
  docs/build/zkEVM/quickstart.md
Labels: documentation

#643 add magic
  docs/build/zkEVM/integrations/account-abstraction/Magic.md
  docs/build/zkEVM/integrations/account-abstraction/index.md
Labels: documentation

#550 Polish The Graph doc
  .gitignore
  docs/build/integrations/indexers/thegraph.md
  docs/build/zkEVM/integrations/indexers/img/thegraph1-logo.jpg
  docs/build/zkEVM/integrations/indexers/img/thegraph14-astar-zkevm-networks.png
  docs/build/zkEVM/integrations/indexers/thegraph.md
Labels: documentation

#646 Update dia.md
  docs/build/integrations/oracles/dia.md
Labels: documentation

#649 zkEVM User Guides 2
  docs/use/zkevm-guides/ASTR-Liquid-Staking.md
  docs/use/zkevm-guides/Bridge-Astar-EVM.md
  docs/use/zkevm-guides/Bridge-Ethereum.md
  docs/use/zkevm-guides/img/Bifrost_1.png
  docs/use/zkevm-guides/img/Bifrost_2.png
  docs/use/zkevm-guides/img/Bifrost_3.png
  docs/use/zkevm-guides/img/Bifrost_4.png
  docs/use/zkevm-guides/img/Bifrost_5.png
  docs/use/zkevm-guides/img/Bifrost_6.png
  docs/use/zkevm-guides/img/Bridge_ETH_1.png
  docs/use/zkevm-guides/img/Bridge_ETH_10.png
  docs/use/zkevm-guides/img/Bridge_ETH_11.png
  docs/use/zkevm-guides/img/Bridge_ETH_2.png
  docs/use/zkevm-guides/img/Bridge_ETH_3.png
  docs/use/zkevm-guides/img/Bridge_ETH_4.png
  docs/use/zkevm-guides/img/Bridge_ETH_5.png
  docs/use/zkevm-guides/img/Bridge_ETH_6.png
  docs/use/zkevm-guides/img/Bridge_ETH_7.png
  docs/use/zkevm-guides/img/Bridge_ETH_8.png
  docs/use/zkevm-guides/img/Bridge_ETH_9.png
  docs/use/zkevm-guides/img/Bridge_ETH_Layerswap_1.png
  docs/use/zkevm-guides/img/Bridge_ETH_Layerswap_2.png
  docs/use/zkevm-guides/img/Bridge_ETH_Layerswap_3.png
  docs/use/zkevm-guides/img/Bridge_ETH_Portal_1.png
  docs/use/zkevm-guides/img/Bridge_ETH_Portal_2.png
  docs/use/zkevm-guides/img/Bridge_ETH_Portal_3.png
  docs/use/zkevm-guides/img/Bridge_ETH_Portal_4.png
  docs/use/zkevm-guides/img/Bridge_ETH_Portal_5.png
  docs/use/zkevm-guides/img/Bridge_ETH_Portal_6.png
  docs/use/zkevm-guides/img/Bridge_ETH_Portal_7.png
  docs/use/zkevm-guides/img/Bridge_ETH_Portal_8.png
  docs/use/zkevm-guides/img/Bridge_ETH_Relaylink_1.png
  docs/use/zkevm-guides/img/Bridge_ETH_Relaylink_2.png
  docs/use/zkevm-guides/img/Bridge_ETH_Relaylink_3.png
  docs/use/zkevm-guides/img/Bridge_ETH_Relaylink_4.png
  docs/use/zkevm-guides/img/Stargate_1.png
  docs/use/zkevm-guides/img/Stargate_2.png
  docs/use/zkevm-guides/img/Stargate_3.png
  docs/use/zkevm-guides/img/Stargate_4.png
  docs/use/zkevm-guides/img/Stargate_5.png
  docs/use/zkevm-guides/img/Stargate_6.png
  i18n/ja/docusaurus-plugin-content-docs/current/use/zkevm-guides/ASTR-Liquid-Staking.md
  i18n/ja/docusaurus-plugin-content-docs/current/use/zkevm-guides/Bridge-Astar-EVM.md
  i18n/ja/docusaurus-plugin-content-docs/current/use/zkevm-guides/Bridge-Ethereum.md
Labels: documentation, translation

#652 Update Astar zkEVM testnet info
  docs/build/zkEVM/quickstart.md
  docs/learn/zkEVM/quickstart.md
Labels: documentation

#653 Fix/zkevm kyoto
  docs/build/zkEVM/zk-node/setup-testnet-rpc-node.md
Labels: documentation
